# Generated by Django 5.2.7 on 2025-11-01 13:36

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailcore", "0095_groupsitepermission"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("description", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name": "Article Category Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("hero_banner", 9),
                    ("mission_vision", 16),
                    ("focus_areas", 23),
                    ("featured_programs", 29),
                    ("latest_articles", 33),
                    ("partners_carousel", 38),
                    ("testimonials", 46),
                    ("newsletter", 52),
                    ("donation_cta", 56),
                    ("impact_stats", 61),
                    ("footer", 67),
                    ("calm_mode_toggle", 70),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main headline",
                            "max_length": 140,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short subtitle or strapline", "required": False},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Background image (prefer landscape)",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "CSS gradient fallback (e.g. linear-gradient(...))",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Get Help", "max_length": 64, "required": True},
                    ),
                    5: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Join Us", "max_length": 64, "required": False},
                    ),
                    7: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional classes to add to the root element",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("background_image", 2),
                                ("background_gradient", 3),
                                ("cta_primary_text", 4),
                                ("cta_primary_link", 5),
                                ("cta_secondary_text", 6),
                                ("cta_secondary_link", 7),
                                ("extra_classes", 8),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "link"],
                            "help_text": "Brief mission statement",
                            "required": True,
                        },
                    ),
                    11: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "link"],
                            "help_text": "Brief vision statement",
                            "required": True,
                        },
                    ),
                    12: ("wagtail.blocks.CharBlock", (), {"max_length": 140}),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (12,),
                        {
                            "help_text": "List core values (each item)",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional pastel background CSS color or class",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("mission_text", 10),
                                ("vision_text", 11),
                                ("values_list", 13),
                                ("mission_icon", 14),
                                ("vision_icon", 14),
                                ("values_icon", 14),
                                ("background_color", 15),
                            ]
                        ],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 140, "required": False},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 80, "required": True},
                    ),
                    19: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description", "required": True},
                    ),
                    20: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional inline SVG markup or icon name",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 18),
                                ("description", 19),
                                ("icon_svg", 20),
                                ("cta_url", 7),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.ListBlock",
                        (21,),
                        {
                            "help_text": "Add 3 or more focus area cards (Awareness, Support, Collaboration, ...)",
                            "max_length": 6,
                            "min_length": 3,
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("grid_title", 17), ("areas", 22)]],
                        {},
                    ),
                    24: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    25: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["home.ProgramPage"], "required": False},
                    ),
                    26: (
                        "wagtail.blocks.ListBlock",
                        (25,),
                        {"help_text": "Manual selection (optional)", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "If true, auto-select featured ProgramPage entries",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 6,
                            "help_text": "Maximum programs to show",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 24),
                                ("programs", 26),
                                ("auto_query", 27),
                                ("limit", 28),
                            ]
                        ],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Latest Articles", "required": False},
                    ),
                    31: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "help_text": "Number of articles to show initially",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Optional category filter",
                            "page_type": ["home.ArticleCategoryPage"],
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 30), ("count", 31), ("category_filter", 32)]],
                        {},
                    ),
                    34: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 140, "required": True},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("partner_logo", 34),
                                ("partner_name", 35),
                                ("website_url", 7),
                            ]
                        ],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.ListBlock",
                        (36,),
                        {
                            "help_text": "List of partner logos, names, and optional website links"
                        },
                    ),
                    38: ("wagtail.blocks.StructBlock", [[("partners", 37)]], {}),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 120, "required": True},
                    ),
                    40: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 39),
                                ("quote", 40),
                                ("photo", 14),
                                ("video_link", 7),
                            ]
                        ],
                        {},
                    ),
                    42: ("wagtail.blocks.ListBlock", (41,), {}),
                    43: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    44: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 7000,
                            "help_text": "Milliseconds between auto slides",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "required": False},
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("testimonials", 42),
                                ("autoplay", 43),
                                ("autoplay_interval", 44),
                                ("show_dots", 45),
                            ]
                        ],
                        {},
                    ),
                    47: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Join our newsletter", "required": False},
                    ),
                    48: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description text", "required": False},
                    ),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Enter your email", "required": False},
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Subscribe", "required": False},
                    ),
                    51: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "/newsletter/subscribe/",
                            "help_text": "AJAX endpoint for subscription",
                            "required": False,
                        },
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 47),
                                ("text", 48),
                                ("placeholder", 49),
                                ("button_text", 50),
                                ("endpoint", 51),
                            ]
                        ],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 180, "required": True},
                    ),
                    54: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Donate Now", "required": False},
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 53),
                                ("description", 54),
                                ("button_text", 55),
                                ("donation_url", 5),
                                ("include_illustration", 43),
                                ("illustration_image", 14),
                            ]
                        ],
                        {},
                    ),
                    57: ("wagtail.blocks.IntegerBlock", (), {"required": True}),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 14), ("label", 18), ("value", 57)]],
                        {},
                    ),
                    59: (
                        "wagtail.blocks.ListBlock",
                        (58,),
                        {
                            "help_text": "Add 3-4 statistic items with label and numeric value"
                        },
                    ),
                    60: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 2000,
                            "help_text": "Duration of count-up animation in milliseconds",
                            "required": False,
                        },
                    ),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("stats", 59), ("duration_ms", 60)]],
                        {},
                    ),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 18), ("url", 5)]],
                        {},
                    ),
                    63: ("wagtail.blocks.ListBlock", (62,), {"required": False}),
                    64: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("facebook", "Facebook"),
                                ("twitter", "Twitter"),
                                ("instagram", "Instagram"),
                                ("youtube", "YouTube"),
                                ("linkedin", "LinkedIn"),
                            ]
                        },
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("network", 64), ("url", 5)]],
                        {},
                    ),
                    66: ("wagtail.blocks.ListBlock", (65,), {"required": False}),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("mission_quote", 54),
                                ("links", 63),
                                ("newsletter_enabled", 45),
                                ("social_links", 66),
                            ]
                        ],
                        {},
                    ),
                    68: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Calm Mode", "required": False},
                    ),
                    69: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional description for the toggle",
                            "required": False,
                        },
                    ),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 68), ("description", 69)]],
                        {},
                    ),
                },
                help_text="Add different sections to the homepage",
                verbose_name="Homepage Content Section",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="header_background",
            field=models.ForeignKey(
                blank=True,
                help_text="Background image for the header",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Optional introduction text for the homepage"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="seo_keywords",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of keywords for SEO",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("paragraph", 0), ("image", 1)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link"]},
                            ),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                        },
                    ),
                ),
                ("published_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="home.articlecategorypage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ProgramPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("description", wagtail.fields.RichTextField(blank=True)),
                ("featured", models.BooleanField(default=False)),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
